default_stages: [pre-commit]
default_install_hook_types:
  [pre-commit, prepare-commit-msg, commit-msg, post-commit, pre-push]

ci:
  skip:
    - mirror-check
    - no-commit-to-branch

repos:
  - repo: https://github.com/George-Ogden/mirror-rorrim/
    rev: v0.4.9
    hooks:
      - id: mirror-check
        fail_fast: true

  - repo: https://github.com/pre-commit/pre-commit-hooks/
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch
        fail_fast: true
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: mixed-line-ending
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: requirements-txt-fixer

  - repo: https://github.com/George-Ogden/linter/
    rev: v2.1.1
    hooks:
      - id: lint
        args: [--fix]

  - repo: https://github.com/koalaman/shellcheck-precommit/
    rev: v0.11.0
    hooks:
      - id: shellcheck
        args: [--severity=warning]

  - repo: https://github.com/astral-sh/ruff-pre-commit/
    rev: v0.15.11
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
        args: [--config, format.skip-magic-trailing-comma = true]

  - repo: https://github.com/pre-commit/mirrors-prettier/
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: ^docs/

  - repo: https://github.com/rhysd/actionlint/
    rev: v1.7.12
    hooks:
      - id: actionlint

  - repo: https://github.com/codespell-project/codespell/
    rev: v2.4.2
    hooks:
      - id: codespell

  - repo: https://github.com/George-Ogden/pre-commit-hooks/
    rev: v3.1.0
    hooks:
      - id: check-merge-conflict
      - id: dbg-check
      - id: todo-check
        exclude: (?x)^(
          .pre-commit-config.yaml|
          .gitignore|
          utils/(__init__.py|errors(.py|_test.py))
          )$
      - id: mypy
        args: [-r, requirements-dev.txt, --show-traceback]
      - id: spell-check-commit-msgs
      - id: mirror-auto-msg
      - id: version-txt-auto-msg
