[pytest]
python_files = *_test.py test_utils.py
addopts = --capture=sys -m "not slow" --timeout 60 --timeout-method=thread --inline-snapshot=review
pythonpath = .
markers =
    typed: marks tests for type checking
    slow: affects the runtime of the test suite
    local: skip on the remote test server
