line-length = 100

[format]
quote-style = "double"
indent-style = "space"

[lint]
extend-select = ["B", "C4", "COM818", "ERA", "F", "I", "ISC", "N", "PT", "PYI", "RET", "RUF", "SIM", "UP", "W"]
extend-ignore = ["C408", "E501", "F811", "PLC0414", "PT011", "PT012", "PT013", "PYI041", "RET504", "S", "SIM118", "TRY"]
extend-unfixable = ["B905", "B911", "B912", "PT006"]
preview = true

[lint.isort]
force-sort-within-sections = true
split-on-trailing-comma = false

[lint.flake8-pytest-style]
parametrize-names-type = "csv"
