name: Run Prek Hooks on All Files

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-prek:
    uses: George-Ogden/actions/.github/workflows/lint.yaml@v4.2.0
