name: Tag New Version and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag-and-release:
    uses: George-Ogden/actions/.github/workflows/python-release.yaml@v4.3.0
    with:
      validation-code: "from utils import increment; assert increment(4) == 5"
