name: Run Python Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-pytest:
    uses: George-Ogden/actions/.github/workflows/python-test.yaml@v4.3.0
    with:
      python-versions: "['3.13','3.14']"
      pytest-flags: -vv -m "not local"
